version: "2"
services:
  gitlab:
    image: gitlab/gitlab-ce:8.17.0-ce.0
    container_name: gitlab_sg
    hostname: gitlab_sg
    network_mode: bridge
    privileged: true
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://ip:8886'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = ""
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_user_name'] = ""
        gitlab_rails['smtp_password'] = ""
        gitlab_rails['smtp_domain'] = ""
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    ports:
      - 443:443
      - 8886:8886
      - "22:22"
      - "25:25"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/disk/gitlab/config:/etc/gitlab
      - /mnt/disk/gitlab/logs:/var/log/gitlab
      - /mnt/disk/gitlab/data:/var/opt/gitlab
      - /mnt/disk/gitlab/backups:/var/opt/gitlab/backups/
