version: "3"
services:
  web:
    image: nginx:1.13.5
    container_name: proxy-nginx
    hostname: nginx-host
    network_mode: bridge
    restart: always
    ports:
     - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/conf.d/duang.conf:/etc/nginx/conf.d/duang.conf
#    command: [ 'nginx-debug', '-g', 'daemon off;']

